apiVersion: v1
kind: ConfigMap

metadata:
  name: lovematch-config

data:
  PORT: "5000"
  MONGO_URI: "mongodb://mongo:27017/lovematch"
  BASE_URL: "http://localhost:5000"
  DEFAULT_MATCH_RADIUS: "50"
  MIN_AGE: "18"
  MAX_AGE: "60"
  MAX_DAILY_SWIPES: "100"
  MAX_MESSAGE_LENGTH: "500"