apiVersion: v1
kind: Service

metadata:
  name: lovematch-service

spec:
  type: NodePort

  selector:
    app: lovematch

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30008